# workflow definition
name: Add Project

# workflow trigger definition
on:
  workflow_dispatch:  # manually triggered

    # user input(s) used by workflow
    inputs:
     project-name:
        description: 'a project name'
        required: true
        default: 'project'
     project-body:
        description: 'a project description'
        required: true
        default: 'This project has columns'

# workflow job(s) definition
jobs:
  job-1:
    # define platform required for job
    runs-on: ubuntu-latest
    # description of function performed by the job
    name: add a project, with standard columns to the repo
    
    # steps executed by job
    steps:
    - run: echo "Git hub context ${{toJson(github.event)}}"  # [debug] dump trigger event context info

    # execute job action(s)
    - name: add project with columns
      id: add-project
      # call script defined in <owner>/<repo>/<script> and by @<release> or @<branch>
      uses: vvec/design-management/.github/actions/add-project@main
      # with parameters defined ../<repo>/<script>/action.yml
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        repo-id: ${{github.event.repository.node_id}}
        repo-name: ${{github.event.repository.name}}
        repo-owner: ${{github.event.repository.owner.login}}
        project-name: ${{github.event.inputs.project-name}}
        project-body: ${{github.event.inputs.project-body}}